
defaults = dict(
    n_steps = 200,
    log_every = 25,
    tol = None,
    stop_window = 5,
    batch_size = 100,
    batch_seed = 23,
    mstep_batch_size = None,
    mstep_batch_seed = 29,
    learning_rate = 5e-3,
    scale_lr = False,
    mstep_tol = 1e-7,
    mstep_stop_window = 25,
    mstep_update_max = 1e2,
    update_blacklist = None,
    mstep_n_steps = 2000,
    mstep_log_every = -1,
    return_param_hist = 'trace',
)